error_log  /var/log/nginx/error.log notice;
pid        /var/run/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  300;

    #gzip  on;

    include /etc/nginx/conf.d/*.conf;

    upstream ai {
        # ai host
        # server 10.5.187.190:8000;
        # server 10.206.85.171:4729;
        server 10.38.70.65:3331;
        server 10.38.70.65:3332;
        server 10.38.70.65:3333;
        server 10.38.70.65:3334;
        # server 10.206.85.172:4730;
        # server 10.206.85.173:4730;
        # server 10.206.85.214:4730;
        # server 10.208.204.83:4730;
    }

    server {
        listen 80;
        server_name 10.38.70.65;

        location / {
            # strip the "/ai" prefix from the path when forwarding to
            # rewrite ^/ai(/.*)$ $1 break;
            proxy_pass http://ai;
            proxy_next_upstream error timeout http_502 http_503 http_504 http_429;
            # include proxy_params;
            # proxy_redirect off;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_read_timeout 300;
        }
    }
}

